WAVE_TWO = [
  { type: :basic, column: 1, time: 0.00, args: [:normal] },
  { type: :basic, column: 7, time: 0.50, args: [:normal] },
  { type: :basic, column: 2, time: 1.00, args: [:normal] },
  { type: :basic, column: 6, time: 1.50, args: [:normal] },
  { type: :basic, column: 3, time: 2.00, args: [:normal] },
  { type: :basic, column: 5, time: 2.50, args: [:normal] },
  { type: :basic, column: 4, time: 3.00, args: [:normal] },

  { type: :basic, column: 5, time: 5.50, args: [:sin] },
  { type: :basic, column: 2, time: 5.50, args: [:normal] },
  { type: :basic, column: 3, time: 6.00, args: [:sin] },
  { type: :basic, column: 6, time: 6.00, args: [:normal] },
  { type: :basic, column: 5, time: 7.50, args: [:sin] },
  { type: :basic, column: 2, time: 7.50, args: [:normal] },
  { type: :basic, column: 3, time: 8.00, args: [:sin] },
  { type: :basic, column: 6, time: 8.00, args: [:normal] },

  { type: :basic, column: 1, time: 9.00, args: [:normal] },
  { type: :basic, column: 7, time: 9.00, args: [:normal] },
  { type: :basic, column: 2, time: 9.50, args: [:normal] },
  { type: :basic, column: 6, time: 9.50, args: [:normal] },
  { type: :basic, column: 3, time: 10.00, args: [:normal] },
  { type: :basic, column: 5, time: 10.00, args: [:normal] },
  { type: :basic, column: 4, time: 10.50, args: [:normal] },

  { type: :basic, column: 4, time: 11.50, args: [:normal] },
  { type: :basic, column: 3, time: 12.00, args: [:normal] },
  { type: :basic, column: 5, time: 12.00, args: [:normal] },
  { type: :basic, column: 2, time: 12.50, args: [:normal] },
  { type: :basic, column: 6, time: 12.50, args: [:normal] },
  { type: :basic, column: 1, time: 13.00, args: [:normal] },
  { type: :basic, column: 7, time: 13.00, args: [:normal] },
]
